### ISSUE TITLE
Plans?

### ISSUE THREAD

**Issue by sbromberger** [JuliaGraphs/Networks.jl#5]
Hey - are we planning on doing anything with this? If so, we might want to rename it LGNetworks.jl or something if it's going to be a submodule.

**Comment by evanfields** [comment]
It seems like the Julia ecosystem should have a high quality package that can represent something like a weighted graph. If `Graphs` is in danger of being unmaintained, do we? Intuitively this package seems important. 

I was thinking to move `TravelingSalesmanHeuristics` off the `Graphs` dependency, which requires an alternate minimum spanning tree implementation. In the next few days I could do a simple implementation here, if this package is likely to stick around?

**Comment by CarloLucibello** [comment]
I would not recommend adding anything here, this package is little more than a placeholder for the time being. 

A more promising package for graphs with vertex and edge properties is here https://github.com/pranavtbhat/Graft.jl, although in the end it relies on the construction of LightGraphs' graphs for many graph computations

In your particolar case I would suggest to keep the weightmap decoupled from the graph structure and submit your TSP heuristic has a contribution to LightGraphs
You can find a similar approach for the maximum  matching problem, where you also have weighted edges, implemented in https://github.com/JuliaGraphs/LightGraphsExtras.jl under src/matching/matching.jl

**Comment by sbromberger** [comment]
@evanfields see [SimpleWeightedGraphs](https://github.com/JuliaGraphs/SimpleWeightedGraphs.jl).
